export const janzuWorkflowData = [
  {
    id: 1,
    header: "Practitioner profile",
    type: "Profile",
    status: "In Process",
    target: "Public",
    limit: "Owner",
    reviewer: "Assign reviewer",
  },
  {
    id: 2,
    header: "Validated sessions",
    type: "Certification",
    status: "In Process",
    target: "50",
    limit: "50",
    reviewer: "Manager",
  },
  {
    id: 3,
    header: "Client CRM",
    type: "Private",
    status: "Done",
    target: "Secure",
    limit: "RLS",
    reviewer: "Admin",
  },
  {
    id: 4,
    header: "Location submissions",
    type: "Review",
    status: "In Process",
    target: "Approved",
    limit: "Queue",
    reviewer: "Assign reviewer",
  },
  {
    id: 5,
    header: "Community events",
    type: "Events",
    status: "Done",
    target: "RSVP",
    limit: "Capacity",
    reviewer: "Manager",
  },
]
